{
 "title": "InterBTC Testnet",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": " Vaults (Non Banned)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "vaults.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  vaults(orderBy: LAST_EVENT_AT_DESC, filter: { bannedUntilBlock:{ isNull: true } } ) {\n    nodes {\n      bannedUntilBlock\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Total Tokens Redeemed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "tokenRedeemEvents.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  tokenRedeemEvents(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\" lessThanOrEqualTo: \"${__to:date:iso}\" }\n  }) {\n    nodes {\n      Time: timestamp\n      Value: amount\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Total Tokens Issued",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "tokenIssueEvents.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  tokenIssueEvents(filter: { \n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\" lessThanOrEqualTo: \"${__to:date:iso}\" }\n  }) {\n    nodes {\n      Time: timestamp\n      Value: amount\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "DOT/BTC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "oracleExchangeRates.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  oracleExchangeRates(filter: { \n    key: { equalTo:\"DOT\" }\n    timestamp: { greaterThanOrEqualTo: \"${__from:date:iso}\" lessThanOrEqualTo: \"${__to:date:iso}\" }\n  }) {\n    nodes {\n      Time: timestamp\n      Value: value\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": " Vaults (Non Banned)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "vaults.nodes",
     "endTimePath": "endTime",
     "queryText": "query {\n  vaults(orderBy: LAST_EVENT_AT_DESC, filter: { bannedUntilBlock:{ isNull: true } } ) {\n    nodes {\n      bannedUntilBlock\n    }\n  }\n}"
    }
   ]
  }
 ]
}